"""Contracts a service imports from an installed distribution, never emits.

A contract several services share (the AgentGateway API, say) is generated
once, by its own distribution, and every consumer imports that one copy. Two
consumers that each compiled the same ``.proto`` would register it twice in
protobuf's global descriptor pool, and a message one passes to the other would
be two different classes.

Such a distribution follows the layout every ``<repo>-grpc`` distribution
already has: a package holding the contract's sources under ``proto/`` and the
code generated from them under ``generated/``. A codegen target names the
installed package, and nothing else::

    [[tool.service_toolkit.grpc_proto_codegen.targets]]
    proto_dir = "src/network_service_grpc/proto"
    out_dir = "src/network_service_grpc/generated"
    import_prefix = "network_service_grpc.generated.leavepulse"
    imports = ["agent_contract_grpc"]

The installed package is the one source of truth: its ``proto/`` goes on the
compiler's include path, its files are not compiled, and every generated
import of a module it defines is pointed at its ``generated/`` tree. Which
modules those are is read from the files it ships, so a file the contract adds
needs no change in any consumer, and the protos a consumer compiles against are
always those of the generated code it runs with.
"""

from __future__ import annotations

import importlib.util
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

PROTO_DIR = "proto"
GENERATED_DIR = "generated"


class ImportedContractError(SystemExit):
    """An imported contract that is missing or not laid out as one."""


@dataclass(frozen=True, slots=True)
class ImportedContract:
    """A contract generated by an installed distribution."""

    #: The installed Python package, e.g. ``agent_contract_grpc``.
    package: str
    #: Its ``.proto`` sources, for the compiler's include path only.
    proto_root: Path
    #: The Python package the generated modules live under.
    import_root: str
    #: Relative paths of every ``.proto`` it defines.
    proto_files: frozenset[PurePosixPath]

    @property
    def modules(self) -> frozenset[str]:
        """The ``*_pb2`` modules its protos generate, by their proto path.

        Per file, not per directory: a consumer may define its own protos in a
        directory the contract also uses (``leavepulse/control/v1``), and those
        stay its own.
        """
        return frozenset(
            ".".join((*path.parent.parts, f"{path.stem}_pb2"))
            for path in self.proto_files
        )


def resolve(package: str) -> ImportedContract:
    """The installed contract *package*, checked for the expected layout."""
    spec = importlib.util.find_spec(package)
    if spec is None or not spec.submodule_search_locations:
        msg = (
            f"imported contract {package} is not an installed package; add its "
            "distribution to this project's dependencies."
        )
        raise ImportedContractError(msg)
    root = Path(next(iter(spec.submodule_search_locations)))
    proto_root = root / PROTO_DIR
    if not (root / GENERATED_DIR).is_dir() or not proto_root.is_dir():
        msg = (
            f"imported contract {package} at {root} has no {PROTO_DIR}/ and "
            f"{GENERATED_DIR}/; it is not a generated contract distribution."
        )
        raise ImportedContractError(msg)
    files = frozenset(
        PurePosixPath(path.relative_to(proto_root).as_posix())
        for path in proto_root.rglob("*.proto")
    )
    if not files:
        msg = f"imported contract {package} ships no .proto files in {proto_root}."
        raise ImportedContractError(msg)
    return ImportedContract(
        package=package,
        proto_root=proto_root,
        import_root=f"{package}.{GENERATED_DIR}",
        proto_files=files,
    )


def import_roots(contracts: Iterable[ImportedContract]) -> dict[str, str]:
    """Each imported ``*_pb2`` module mapped to the Python root that holds it."""
    roots: dict[str, str] = {}
    for contract in contracts:
        for module in contract.modules:
            owner = roots.setdefault(module, contract.import_root)
            if owner != contract.import_root:
                msg = (
                    f"{module} is generated by both "
                    f"{owner} and {contract.import_root}; one owner only."
                )
                raise ImportedContractError(msg)
    return roots


def check_not_redefined(
    own_files: Iterable[PurePosixPath],
    contracts: Iterable[ImportedContract],
) -> None:
    """Refuse a target that would emit a proto an imported contract owns."""
    own = set(own_files)
    for contract in contracts:
        clash = sorted(str(path) for path in own & contract.proto_files)
        if clash:
            msg = (
                f"{', '.join(clash)} belong to the imported contract "
                f"{contract.package}; a consumer imports them, never emits them."
            )
            raise ImportedContractError(msg)
