"""A contract generated by its own distribution is imported, never re-emitted."""

from __future__ import annotations

import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

from service_toolkit.grpc import imported
from service_toolkit.grpc.codegen import (
    _generate_target,
    _rewrite_imports,
    _ProtoGenerationTarget,
    _targets_from_config,
)

# A proto tree no other test registers, so the subprocess checks below see
# exactly these files in the descriptor pool.
CONTRACT_PROTO = """\
syntax = "proto3";
package leavepulse.imptest.v1;
message Policy { string subject = 1; }
"""

CONSUMER_PROTO = """\
syntax = "proto3";
package leavepulse.imptest.v1;
import "leavepulse/imptest/v1/contract.proto";
message Request { Policy policy = 1; }
service Consumer { rpc Send(Request) returns (Request); }
"""


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


@pytest.fixture
def contract_site(tmp_path: Path) -> Path:
    """An installed contract distribution: ``proto/`` and ``generated/``."""
    site = tmp_path / "contract-site"
    package = site / "imptest_contract_grpc"
    _write(package / "__init__.py", "")
    _write(package / "proto/leavepulse/imptest/v1/contract.proto", CONTRACT_PROTO)
    _generate_target(
        _ProtoGenerationTarget(
            proto_dir=package / "proto",
            out_dir=package / "generated",
            import_prefix="imptest_contract_grpc.generated.leavepulse",
        )
    )
    return site


def _consumer(tmp_path: Path) -> _ProtoGenerationTarget:
    package = tmp_path / "consumer-site" / "imptest_consumer_grpc"
    _write(package / "__init__.py", "")
    # Same directory as the contract's file: a consumer's own protos there stay
    # its own.
    _write(package / "proto/leavepulse/imptest/v1/consumer.proto", CONSUMER_PROTO)
    return _ProtoGenerationTarget(
        proto_dir=package / "proto",
        out_dir=package / "generated",
        import_prefix="imptest_consumer_grpc.generated.leavepulse",
        imports=("imptest_contract_grpc",),
    )


def test_an_imported_contract_is_on_the_include_path_and_never_emitted(
    tmp_path: Path, contract_site: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.syspath_prepend(str(contract_site))
    target = _consumer(tmp_path)

    _generate_target(target)

    emitted = sorted(p.name for p in target.out_dir.rglob("*_pb2*.py"))
    assert emitted == ["consumer_pb2.py", "consumer_pb2_grpc.py"]
    source = (target.out_dir / "leavepulse/imptest/v1/consumer_pb2.py").read_text()
    assert (
        "from imptest_contract_grpc.generated.leavepulse.imptest.v1 import "
        "contract_pb2" in source
    )
    grpc_source = (
        target.out_dir / "leavepulse/imptest/v1/consumer_pb2_grpc.py"
    ).read_text()
    # The consumer's own module, in the same proto directory, stays its own.
    assert (
        "from imptest_consumer_grpc.generated.leavepulse.imptest.v1 import "
        "consumer_pb2" in grpc_source
    )


def test_a_pass_through_message_is_the_contract_class_registered_once(
    tmp_path: Path, contract_site: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.syspath_prepend(str(contract_site))
    target = _consumer(tmp_path)
    _generate_target(target)

    # A fresh interpreter: the descriptor pool is process-global, and this test
    # is about what one process registers.
    check = textwrap.dedent(
        """
        import sys
        sys.path[:0] = sys.argv[1:3]
        from google.protobuf import descriptor_pool
        from imptest_contract_grpc.generated.leavepulse.imptest.v1 import contract_pb2
        from imptest_consumer_grpc.generated.leavepulse.imptest.v1 import consumer_pb2

        policy = contract_pb2.Policy(subject="wg")
        request = consumer_pb2.Request(policy=policy)
        assert type(request.policy) is contract_pb2.Policy
        pool = descriptor_pool.Default()
        found = pool.FindFileByName("leavepulse/imptest/v1/contract.proto")
        assert found is contract_pb2.DESCRIPTOR
        assert list(consumer_pb2.DESCRIPTOR.dependencies) == [found]
        """
    )
    result = subprocess.run(  # noqa: S603
        [
            sys.executable,
            "-c",
            check,
            str(contract_site),
            str(target.out_dir.parents[1]),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr


def test_a_target_may_not_emit_a_proto_an_imported_contract_owns(
    tmp_path: Path, contract_site: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.syspath_prepend(str(contract_site))
    target = _consumer(tmp_path)
    _write(target.proto_dir / "leavepulse/imptest/v1/contract.proto", CONTRACT_PROTO)

    with pytest.raises(SystemExit, match="imported contract imptest_contract_grpc"):
        _generate_target(target)


def test_an_imported_contract_must_be_installed() -> None:
    with pytest.raises(SystemExit, match="not an installed package"):
        imported.resolve("imptest_nowhere_grpc")


def test_one_module_has_one_owner(
    contract_site: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.syspath_prepend(str(contract_site))
    contract = imported.resolve("imptest_contract_grpc")
    twin = imported.ImportedContract(
        package="imptest_twin_grpc",
        proto_root=contract.proto_root,
        import_root="imptest_twin_grpc.generated",
        proto_files=contract.proto_files,
    )

    assert imported.import_roots([contract]) == {
        "leavepulse.imptest.v1.contract_pb2": "imptest_contract_grpc.generated"
    }
    with pytest.raises(SystemExit, match="one owner only"):
        imported.import_roots([contract, twin])


def test_rewriting_routes_each_module_to_its_owner(tmp_path: Path) -> None:
    generated = tmp_path / "x_pb2.py"
    generated.write_text(
        "from google.protobuf import descriptor as _descriptor\n"
        "from leavepulse.control.v1 import agent_pb2 as a\n"
        "from leavepulse.control.v1 import graph_pb2 as g\n"
        "from leavepulse.routes.v1 import fleet_routes_pb2 as r\n"
    )

    _rewrite_imports(
        tmp_path,
        "svc_grpc.generated.leavepulse",
        {
            "leavepulse.control.v1.agent_pb2": "contract_grpc.generated",
            "leavepulse.routes.v1.fleet_routes_pb2": "contract_grpc.generated",
        },
    )

    assert generated.read_text().splitlines() == [
        "from google.protobuf import descriptor as _descriptor",
        "from contract_grpc.generated.leavepulse.control.v1 import agent_pb2 as a",
        "from svc_grpc.generated.leavepulse.control.v1 import graph_pb2 as g",
        "from contract_grpc.generated.leavepulse.routes.v1 import fleet_routes_pb2 as r",
    ]


def test_a_target_names_its_imports_in_the_manifest(tmp_path: Path) -> None:
    manifest = tmp_path / "pyproject.toml"
    manifest.write_text(
        textwrap.dedent(
            """
            [[tool.service_toolkit.grpc_proto_codegen.targets]]
            proto_dir = "proto"
            out_dir = "generated"
            import_prefix = "svc_grpc.generated.leavepulse"
            imports = ["agent_contract_grpc"]
            """
        )
    )

    [target] = _targets_from_config(manifest)

    assert target.imports == ("agent_contract_grpc",)


def test_imports_must_be_package_names(tmp_path: Path) -> None:
    manifest = tmp_path / "pyproject.toml"
    manifest.write_text(
        textwrap.dedent(
            """
            [[tool.service_toolkit.grpc_proto_codegen.targets]]
            proto_dir = "proto"
            out_dir = "generated"
            import_prefix = "svc_grpc.generated.leavepulse"
            imports = ["agent-contract-grpc"]
            """
        )
    )

    with pytest.raises(SystemExit, match="installed Python package names"):
        _targets_from_config(manifest)


def test_the_buf_workspace_checks_against_the_installed_contract(
    tmp_path: Path, contract_site: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from service_toolkit.grpc import buf_workspace

    monkeypatch.syspath_prepend(str(contract_site))
    target = _consumer(tmp_path)
    manifest = tmp_path / "pyproject.toml"
    manifest.write_text(
        textwrap.dedent(
            f"""
            [[tool.service_toolkit.grpc_proto_codegen.targets]]
            proto_dir = "{target.proto_dir.relative_to(tmp_path).as_posix()}"
            out_dir = "generated"
            import_prefix = "imptest_consumer_grpc.generated.leavepulse"
            imports = ["imptest_contract_grpc"]

            [tool.service_toolkit.buf.lint]
            use = ["STANDARD"]
            """
        )
    )

    workspace = buf_workspace.build_workspace(manifest)

    assert (
        workspace / "modules/imptest_contract_grpc/leavepulse/imptest/v1/contract.proto"
    ).read_text() == CONTRACT_PROTO
